version: '3.2'

services:
  osrm-backend:
    image: osrm/osrm-backend
    volumes:
      - $PWD/data:/data
    command:
      - 'osrm-routed'
      - '--algorithm'
      - 'mld'
      - '/data/moldova-latest.osrm'
    ports:
      - 5000:5000
    restart: unless-stopped
  osrm_frontend:
     image: osrm/osrm-frontend
     ports: 
      - 9966:9966
     restart: unless-stopped
